include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error
    implicit_dynamic: error

linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
